version: "3"
services:
  web:
    # build: .                  # Only if you want to Build the image on your own Server!
    image: registry.ucode.space/phil/goshorly:latest
    environment:
      - HOST=127.0.0.1          # Domain or IP-Adress
      - PORT=3000               # The Port you want to use
      - HTTPS=true              # If you want to use HTTPS
      - PROXY=true              # If you want to use a Reverse Proxy
      - REDIS_URI=redis         # The Redis-URI (name of redis container OOTB)
      - ENABLE_STATS=true       # Enables the /stats public frontend
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:  
      - db:/data
    restart: always

  caddy:
    image: caddy:2
    restart: always
    command: caddy reverse-proxy --from https://example.org:443 --to http://web:3000
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
    depends_on:
      - web
      - redis

volumes:
  caddy:
  db:
